mdapi/ExerciseAndTherapy/objects/Class__c.object
<CustomObject>
    <description>This is where you define the classes that you will give.  It include information like location, max number of attendees (You can exceed this but should be warned) the usual frequency (used for scheduling future classes) and if it runs on public holidays (used in scheduling)</description>
    <fields>
        <fullName>Casual_Price__c</fullName>
        <inlineHelpText>Enter the normal price for an attendee who &quot;pays as they go&quot;</inlineHelpText>
        <label>Casual Price</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Class_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class Type</label>
        <referenceTo>Class_Type__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Concession_Price__c</fullName>
        <inlineHelpText>The price for this class when a concession (pre-pay) card is used to pay for it.  It defaults to a 10% discount from the casual price</inlineHelpText>
        <label>Concession Price</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Captain&apos;s Retreat</fullName>
                </value>
                <value>
                    <fullName>Pt Chev Tennis Club</fullName>
                </value>
                <value>
                    <fullName>Mt Albert Bowling Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/ExerciseAndTherapy/objects/Class_Attendance__c.object
<CustomObject>
    <description>The occurrence of a student attending a class.  Used to track what classes they received and paid for, if canceled and fee forfeit for late notice</description>
    <fields>
        <fullName>Actual_Cost__c</fullName>
        <description>If cancelled with more that a day&apos;s notice, then no charge for this class, otherwise full cost for the class will be applied</description>
        <formula>IF(  ISPICKVAL( Status__c , &quot;Canceled&quot;) &amp;&amp; NOT Cancellation_Fee_Due__c, 0,
IF  (ISPICKVAL( Payment_Method__c, &quot;Casual&quot;), Scheduled_Class__r.Class__r.Casual_Price__c,
    IF  (ISPICKVAL( Payment_Method__c, &quot;Concession Card&quot;),  Scheduled_Class__r.Class__r.Concession_Price__c ,
        IF  (ISPICKVAL(  Payment_Method__c, &quot;On Account&quot;),  Scheduled_Class__r.Class__r.On_Account_Price__c, 0 ))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If cancelled with more that a day&apos;s notice, then no charge for this class, otherwise full cost for the class will be applied</inlineHelpText>
        <label>Actual Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Sessions__c</fullName>
        <description>Number of session that are charged for attending this class.  If cancelled with more that 1 day&apos;s notice then no charge will be applied</description>
        <formula>IF( ISPICKVAL( Status__c , &quot;Canceled&quot;) &amp;&amp; NOT Cancellation_Fee_Due__c, 0, Scheduled_Class__r.Class__r.Session_Count__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Sessions</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <inlineHelpText>If a person cancels, this can be used to determine if fees are forfeit for late notice</inlineHelpText>
        <label>Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Fee_Due__c</fullName>
        <description>If less than one day&apos;s notice given on cancellation then the class fee is payable</description>
        <formula>Class_Date__c -  Cancel_Date__c &lt;1</formula>
        <label>Cancellation Fee Due</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Date__c</fullName>
        <formula>Scheduled_Class__r.Class_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <formula>Scheduled_Class__r.Class__r.Name</formula>
        <label>Class Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Concession_Card__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Concession Card</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Concession Card is not allocated to this Student</errorMessage>
            <filterItems>
                <field>Concession_Card__c.Card_Expired__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Concession_Card__c</referenceTo>
        <relationshipLabel>Class Attendances</relationshipLabel>
        <relationshipName>Class_Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Price Basis</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Casual</fullName>
                    <default>true</default>
                    <label>Casual</label>
                </value>
                <value>
                    <fullName>Concession Card</fullName>
                </value>
                <value>
                    <fullName>On Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Class__c</fullName>
        <label>Scheduled Class</label>
        <referenceTo>Scheduled_Class__c</referenceTo>
        <relationshipLabel>Class Attendances</relationshipLabel>
        <relationshipName>Class_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waitlist - Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The record selected is not an individual who can be booked on a Scheduled Class</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Class Attendances</relationshipLabel>
        <relationshipName>Class_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Class Attendance</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Class Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/ExerciseAndTherapy/objects/Class_Type__c.object
<CustomObject>
    <description>A collection of common properties as some minimum common attributes.  i.e. an in-house may class would be a different class type from a mat class delivered on behalf of an external organisation.  An in-house private equipment class would be another</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Group Class</fullName>
                </value>
                <value>
                    <fullName>Semi-Private</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class Type</label>
    <nameField>
        <label>Class Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/ExerciseAndTherapy/objects/Concession_Card__c.object
<CustomObject>
    <description>Allows a customer to prepay for classes in return for a discount
Entitles a customer to a number of classes - if the price goes up while the card is still valid, the number of classes the student is entitled to does not reduce.</description>
    <fields>
        <fullName>Sessions_Balance__c</fullName>
        <formula>Sessions__c - Sessions_Used__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label># Sessions Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sessions_Used__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Sessions Used</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sessions__c</fullName>
        <inlineHelpText>The number of classes purchased with this card. Default = 10</inlineHelpText>
        <label># Sessions</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Concession Card</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Concession Card #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concession Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/ExerciseAndTherapy/objects/Scheduled_Class__c.object
<CustomObject>
    <description>Instances of when a Class is actually run - needs a date &amp; time as a minimum</description>
    <fields>
        <fullName>Casual_Price__c</fullName>
        <formula>Class__r.Casual_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Casual Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Class_Date__c</fullName>
        <label>Class Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Scheduled Classes</relationshipLabel>
        <relationshipName>Scheduled_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Concession_Price__c</fullName>
        <formula>Class__r.Concession_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Concession Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The place where the Scheduled Class takes place.  Denormalised from parent Class record</description>
        <formula>Class__r.Location_Copy__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The place where the Scheduled Class takes place (looked up from parent Class record)</inlineHelpText>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proposed</fullName>
                    <default>true</default>
                    <label>Proposed</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Class__r.Class_Type__r.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waitlist_Length__c</fullName>
        <label>Waitlist Length</label>
        <summaryFilterItems>
            <field>Class_Attendance__c.Status__c</field>
            <operation>equals</operation>
            <value>Waitlisted</value>
        </summaryFilterItems>
        <summaryForeignKey>Class_Attendance__c.Scheduled_Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Scheduled Class</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scheduled Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EandT/main/default/classes/ClassAPEXController.cls
Public without sharing class ClassAPEXController {
    
    @AuraEnabled
    public Static List<sObject> myFutureClasses (ID StudentID ) { 
        // We are querying for future classes where this student is an attendee
        // and the future class has not been canceled
        return [SELECT Id, Class_Date__c, Class_Name__c, Status__c, 
                Actual_Cost__c, Actual_Sessions__c, Cancel_Date__c,
                Cancellation_Fee_Due__c, Concession_Card__c, Payment_Method__c,
                Scheduled_Class__c, Scheduled_Class__r.Location__c, Scheduled_Class__r.Status__c,
                Scheduled_Class__r.Type__c
                FROM Class_Attendance__c
                where Student__c = :StudentID AND Class_Date__c >= Today
                AND Scheduled_Class__r.Status__c != 'Canceled'
                Order by Class_Date__c ASC
               ];
    }
    
    @AuraEnabled
    public Static List<sObject> myPriorClasses (ID StudentID ) { 
        // We are querying for prior classes where this student is an attendee
        // and the class itself was not canceled
        return [SELECT Id, Class_Date__c, Class_Name__c, Status__c, 
                Actual_Cost__c, Actual_Sessions__c, Cancel_Date__c,
                Cancellation_Fee_Due__c, Concession_Card__c, Payment_Method__c,
                Scheduled_Class__c, Scheduled_Class__r.Location__c, Scheduled_Class__r.Status__c,
                Scheduled_Class__r.Type__c
                FROM Class_Attendance__c
                where Student__c = :StudentID AND Class_Date__c < Today
                AND Scheduled_Class__r.Status__c != 'Canceled'
                Order by Class_Date__c DESC
               ];
    }
    
    @AuraEnabled
    public Static Scheduled_Class__c ClassDetails(ID SchedClassID) {
        // Find the details of the selected class
        system.debug('Looking for details for class id:' +  SchedClassID);
        
        return [Select ID, 	Class__r.Name, Class_date__c, Casual_Price__c, Concession_Price__c, Location__c, Type__c, Waitlist_Length__c
                from Scheduled_Class__c where ID = :SchedClassID];
    }
    
    @AuraEnabled
    public Static Concession_Card__c myBestConcessionCard (ID StudentID, ID SchedClassID) {
        
        // Find the date and type of the selected class
        Scheduled_Class__c ChosenClass = [Select Class_date__c, Type__c from Scheduled_Class__c where ID = :SchedClassID];
        
        System.debug('StudentID:' + StudentID + ', Class Date' + ChosenClass.Class_Date__c.Date());
        
        //Find the corresponding account id to this Community user
        User CommunityUser = [Select contact.AccountId from user where id =:StudentID ];
        
        // Retrieve the best Concession card  - ie shortest dated unexpired card that maps to this Scheduled Class
        try {
            Return [SELECT Id, Name, Sessions__c, Sessions_Balance__c, Sessions_Used__c, Class_Type__r.Name,
                    Value__c, Value_Balance__c, Value_Used__c
                    FROM Concession_Card__c
                    where Customer__c = :CommunityUser.contact.AccountID AND Expiry_Date__c >= :ChosenClass.Class_Date__c.Date()
                    AND Class_type__r.Name = :ChosenClass.Type__c
                    AND Card_Expired__c = FALSE
                    Order by Expiry_Date__c ASC
                    Limit 1
                   ];
        } catch (Exception ex) {
            System.debug('No suitable cards found - returning null');
            Concession_Card__c nullcard = new Concession_Card__c();
            Return nullcard;  // no rows returned.  This user hasn't got a valid concession card for the selected class date and type
            
        }
        
    }
    
    
    @AuraEnabled
    public Static ID RegisterNow(ID SchedClassID, ID StudentID, ID ConCardID, String RegistrationStatus, String PaymentMethod) {
        
        system.debug('RegisterNow: Class ID: '+ SchedClassID + 'Student ID' + StudentID + 'Card ID' + ConCardID + 'RegType: ' + RegistrationStatus);
        // get the contact id for the passed in user / student id
        User Con = [Select contact.account.ID from user where ID = :StudentID];
        Class_Attendance__c CA = new Class_Attendance__c();
        CA.Student__c = Con.contact.account.ID;
        CA.Scheduled_Class__c = SchedClassID;
        CA.Status__c = RegistrationStatus; //'Booked' or 'Waitlisted'
        system.debug('RegisterNow: ID test: '+ string.valueof(ConCardID));
        If (PaymentMethod == 'concard') {
            CA.Concession_Card__c = ConCardID;
            CA.Payment_Method__c = 'Concession Card';
        } else {
            CA.Payment_Method__c = 'Casual';
        }
        system.debug('RegisterNow: Record to insert: ' + CA );
        try {
            insert CA;
        	system.debug('RegisterNow: Inserted record ID:' + CA.ID);
        } catch(DmlException e) {
            System.debug('RegisterNow: An unexpected error has occurred: ' + e.getMessage());
        }
        return CA.Id;
    }
    
@AuraEnabled    
    public Static myClasseswrapper ClasstoCancel(ID CA_ID){
        // Get details for the class that has been asked to be canceled and return a single record with the details needed
        // 
        List<User> u = [SELECT u.Id,u.ContactId, u.Contact.AccountID
                        FROM User u 
                        WHERE u.Id = :UserInfo.getUserId()
                        AND u.IsActive = True];
        
        ID CurrentUser;
        If (u.size() == 1) {
            CurrentUser=u[0].Contact.AccountID;
        } else {
            CurrentUser= '';
        }
        
        Class_attendance__c CA = [Select ID, Scheduled_Class__c, Status__c, Payment_Method__c, Actual_Cost__c, Actual_Sessions__c      
               					From Class_attendance__c 
                               where ID= :CA_ID];
        
        Scheduled_Class__c SC = [Select ID, Name, Class_Date__c, Location__c, Open_Places__c, Type__c, Waitlist_Length__c, Status__c, Class__r.Name
                                FROM Scheduled_Class__c 
                                Where ID=:CA.Scheduled_Class__c];
        
        Return new myClasseswrapper(SC, CA.Status__c, CurrentUser, CA.ID, CA.Payment_Method__c, CA.Actual_Cost__c, CA.Actual_Sessions__c);


    }
    
    
    
    @AuraEnabled
    public Static List<myClasseswrapper> AllFutureClasses() { 
        // We are querying for future classes. If the current user is an attendee
        // then we need to show that they can't book on it
        // If the user is not logged in, then all classes with spaces show as bookable
        // If the class is full, then show that.  If the student is booked on a full class then show they are booked
        // 
        // If the session is anonymous then the Guest user ID will have no assigned classes 
        
        // Find the ID of the Current Logged in user or return '' if not logged in
        // This may actually return the Guest user If session is anonymous
        List<User> u = [SELECT u.Id,u.ContactId, u.Contact.AccountID
                        FROM User u 
                        WHERE u.Id = :UserInfo.getUserId()
                        AND u.IsActive = True];
        
        ID CurrentUser;
        If (u.size() == 1) {
            CurrentUser=u[0].Contact.AccountID;
        } else {
            CurrentUser= '';
        }
        
        System.debug('Logged in user is: ' + CurrentUser);
        
        List<Scheduled_Class__c> FutureClassList =  [SELECT ID, Class_Date__c, Class__r.Name, Location__c, Open_Places__c, Type__c,Waitlist_Length__c,
                                                     Status__c, Class__r.Do_not_expose_to_Community__c 
                                                     FROM Scheduled_Class__c
                                                     where Class_Date__c >= Today
                                                     AND Status__c != 'Canceled'
                                                     Order by Class_Date__c ASC];
        
        List<Class_Attendance__c> myFutureAttendances = [SELECT ID, Scheduled_Class__c, Status__c, 	Payment_Method__c, 
                                                         Actual_Cost__c, Actual_Sessions__c
                                                         FROM Class_Attendance__c 
                                                         Where Student__c = :CurrentUser AND Scheduled_Class__c in :FutureClassList
                                                         // AND (Status__c = 'Booked' OR Status__c = 'Waitlisted') - removed to allow "hidden" classes to be exposed to community
                                                         ORDER BY Class_Date__c ASC];
        //Create map of My Future attendance statuses, payment methods, costs, sessions etc with the ID of the Scheduled Class as the index
        Map<Id, String> StatusMap = new Map<Id, String>();
        Map<Id, Id> ClsAttendanceIDMap = new Map<Id, ID>();
        Map<Id, String> ClsAttendancePaymentMap = new Map<Id, String>();        
        Map<Id, Decimal> ClsAttendanceCostMap = new Map<Id, Double>();        
        Map<Id, Decimal> ClsAttendanceSessionMap = new Map<Id, Double>();        
		// This map holds all classes attended
        Map<Id, Id> ClsEverBookedIDMap = new Map<Id, ID>();

		// Build all the required Maps
        For (integer i=0; i<myFutureAttendances.size(); i++ ) {
            if (myFutureAttendances[i].Status__c=='Booked' || myFutureAttendances[i].Status__c=='Waitlisted') {
                // only populate the Maps if there is a current booking or waitlisting record
                StatusMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].Status__c);
                ClsAttendanceIDMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].ID);
                ClsAttendancePaymentMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].Payment_Method__c);
                ClsAttendanceCostMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].Actual_Cost__c);
                ClsAttendanceSessionMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].Actual_Sessions__c);
            }
            // Add the Class Attendance ID to the map containing calsses that have ever been attended so we can expose these classes
            // to authenticated users even if the classes are mrked as not to be exposed on the Community page
            // (See help text for Class__c.Do_not_expose_to_Community__c field for an explanation of why )
            ClsEverBookedIDMap.put(myFutureAttendances[i].Scheduled_Class__c, myFutureAttendances[i].ID);
        }
        
        
        List<myClasseswrapper> myClassList = new List<myClasseswrapper>();
        
        for (Scheduled_Class__c   c : FutureClassList){
            If (StatusMap.ContainsKey(c.ID)) { //then there is a current booking or waitlisting record so it is safe to expose on the community
                myClassList.add(new myClasseswrapper(c, StatusMap.get(c.ID), CurrentUser, ClsAttendanceIDMap.get(c.ID),
                                                    ClsAttendancePaymentMap.get(c.ID), ClsAttendanceCostMap.get(c.ID), ClsAttendanceSessionMap.get(c.ID)));
            } else {
                If (!c.Class__r.Do_not_expose_to_Community__c) { // If there is no restriction on showing this class to the community add it
                    myClassList.add(new myClasseswrapper(c, '', CurrentUser, null, null, null, null));
                } else {
                    if (ClsEverBookedIDMap.ContainsKey(c.ID)) { // if there is a restriction, only expose it if this user has an attendance record at any status
                        myClassList.add(new myClasseswrapper(c, '', CurrentUser, null, null, null, null));
                    }
                }
            }
        }

        For (  myClasseswrapper mcw : myClassList) {
                    system.debug('Returned record: ' + mcw);
        }   

        
        return myClassList;
    }       
    
    Public class myClasseswrapper
    {
        @AuraEnabled
        public ID ClsID {get; set;}
        @AuraEnabled
        public datetime ClsDate {get; set;}
        @AuraEnabled
        public String ClsName {get; set;}
        @AuraEnabled
        public String ClsLocation {get; set;}
        @AuraEnabled
        public Double ClsPlaces {get; set;}  // The number of places available
        @AuraEnabled
        Public String ClsType {get; set;}
        @AuraEnabled
        Public String ClsListStatus {get; set;} // This is the status value for the class to be displayed on the list - i.e. places available or Full
        @AuraEnabled
        public String StudentStatus {get; set;} //This is the Class_Attendance status (Booked, Waitlisted etc)
        @AuraEnabled
        public String ClsStudentID {get; set;}
        @AuraEnabled
        public String ClsAttendanceID {get; set;}
        @AuraEnabled
        public Double ClsWaitlistLength {get; set;}
        @AuraEnabled
        public String ClsPaymentMethod {get; set;}
        @AuraEnabled
        public Decimal ClsCost {get; set;}
        @AuraEnabled
        public Decimal ClsSessions {get; set;}
        @AuraEnabled        
        public Boolean ClsCancelFeeDue {get; set;}
        @AuraEnabled
        public String eventType {get; set;}
        @AuraEnabled 
        public String variant {get; set;}
        public myClasseswrapper(Scheduled_Class__c SC, String AttStatus, ID ThisUser, ID AttendeesClassID, 
                                String AttPaymentMethod, Decimal AttCost, Decimal AttSessions)
        {
            ClsID = SC.ID;
            ClsDate = SC.Class_Date__c;
            ClsName = SC.Class__r.Name;
            ClsLocation = SC.Location__c;
            ClsPlaces = SC.Open_Places__c;
            ClsType = SC.Type__c;
            if ( SC.Status__c == 'Proposed' ) {
                ClsListStatus = 'Class Planned';
            } else if (SC.Open_Places__c < 1) {
                ClsListStatus = 'Class Full';
            } else {
                ClsListStatus = 'Places Available';
            }
            StudentStatus = AttStatus; //This is the Class_Attendance status (Booked, Waitlisted etc)
            ClsStudentID = ThisUser;
            ClsAttendanceID = AttendeesClassID;
            ClsWaitlistLength = SC.Waitlist_Length__c;
            ClsPaymentMethod = AttPaymentMethod;            
            ClsCost = AttCost;
            ClsSessions = AttSessions;
            ClsCancelFeeDue = (System.now().date() >= SC.Class_Date__c.date() ); // Fee due if canceled on (or after) the day of the class
            if (StudentStatus == 'Booked') {
                eventType = 'Cancel Booking';
                variant = 'destructive';
            } else if (StudentStatus == 'Waitlisted') {
                eventType = 'Cancel Waitlist';
                variant = 'destructive';
            } else if ( (ClsAttendanceID == null) && ((ClsPlaces <1) || (ClsListStatus == 'Class Planned')) ){
                eventType = 'Waitlist Me';
                variant = 'neutral';
            } else if ( (StudentStatus == 'Cancelled') || (StudentStatus == 'Waitlist - Cancelled') || (ClsAttendanceID == null)
                       && (ClsPlaces >0) &&
                       (ClsListStatus != 'Class Planned') && (ClsListStatus != 'Cancelled')) {
                           eventType = 'Register'; 
                           variant = 'brand';
                       } else { 
                           system.debug('Unexpected combination of statuses found:');
                           system.debug('StudentStatus: ' + StudentStatus + ' ClsAttendanceID:' + ClsAttendanceID +
                                        ' ClsPlaces:' + ClsPlaces + ' ClsListStatus: ' + ClsListStatus );
                       }
            
            System.debug('Now: ' + System.now().date() + ' Class Date:' + SC.Class_Date__c.date() + ' Fee due: ' + ClsCancelFeeDue);
            

            
        }
    }
    
    
    @AuraEnabled
    public Static myBookingwrapper mySelectedBooking(ID StudentID, ID SchedClassID) { 
        //Build the Wrapper object to allow the confirmation pop-up to be filled in
        
        System.debug('Best Concession card: ' + myBestConcessionCard(StudentID, SchedClassID));
        System.debug('Selected Class: ' + ClassDetails(SchedClassID));
        myBookingwrapper myBooking = new myBookingwrapper(ClassDetails(SchedClassID),
                                                          myBestConcessionCard(StudentID, SchedClassID));
        
        system.debug('Returned BookingWrapper: ' + myBooking);
        
        return myBooking;
    }    
    
    Public class myBookingwrapper
    {
        @AuraEnabled
        public ID ClsID {get; set;}
        @AuraEnabled
        public datetime ClsDate {get; set;}
        @AuraEnabled
        public String ClsName {get; set;}
        @AuraEnabled
        public String ClsLocation {get; set;}
        @AuraEnabled
        Public String ClsType {get; set;}
        @AuraEnabled
        Public Decimal ClsConcessionPrice {get; set;}        
        @AuraEnabled
        Public Decimal ClsCasualPrice {get; set;} 
        @AuraEnabled
        public Double ClsWaitlistLength {get; set;}
        @AuraEnabled
        public ID ConID {get; set;} 
        @AuraEnabled
        public String ConName {get; set;} 
        @AuraEnabled
        public Decimal ConSessions {get; set;}         
        @AuraEnabled
        public Decimal ConSessionsBalance {get; set;}         
        @AuraEnabled
        public Decimal ConSessionsUsed {get; set;}         
        @AuraEnabled
        public String ConClassType {get; set;}         
        @AuraEnabled
        public Decimal ConValue {get; set;} 
        @AuraEnabled
        public Decimal ConValueBalance {get; set;}         
        @AuraEnabled
        public Decimal ConValueUsed {get; set;} 
        public myBookingwrapper(Scheduled_Class__c SC, Concession_Card__c CC)
        {
            System.debug('In wrapper set up for myBookingWrapper');
            ClsID = SC.ID;
            ClsDate = SC.Class_Date__c;
            ClsName = SC.Class__r.Name;
            ClsLocation = SC.Location__c;
            ClsType = SC.Type__c;
            ClsConcessionPrice = SC.Concession_Price__c;
            ClsCasualPrice = SC.Casual_Price__c;
            ClsWaitlistLength = SC.Waitlist_Length__c;
            ConID = CC.Id;
            ConName = CC.Name;
            ConSessions = CC.Sessions__c;
            ConSessionsBalance = CC.Sessions_Balance__c;
            ConSessionsUsed = CC.Sessions_Used__c;
            ConClassType = CC.Class_Type__r.Name;
            ConValue = CC.Value_Used__c;
            ConValueBalance = CC.Value_Balance__c;
            ConValueUsed= CC.Value_Used__c;
        }
    }
    
    
    @AuraEnabled
    public static ID CancelWaitList(ID ClassAttendanceID) {
        
        Class_Attendance__c WLTC = [Select ID from Class_Attendance__c where ID = :ClassAttendanceID];
        
        WLTC.Status__c = 'Waitlist - Canceled';
        WLTC.Cancel_Date__c = Date.Today();
        
        try {
            update WLTC;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
        return WLTC.Id;
    }

    @AuraEnabled
    public static ID APEXCancelBooking(ID ClassAttendanceID) {
        
        system.debug(' About to cancel Class_Attendance__c.ID=' + ClassAttendanceID);
        Class_Attendance__c CB = [Select ID from Class_Attendance__c where ID = :ClassAttendanceID];
        
        CB.Status__c = 'Canceled';
        CB.Cancel_Date__c = Date.Today();
        
        try {
            update CB;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
        return CB.Id;
    }
    
}